#pragma once

#include <unordered_map>
#include <string>

namespace qlm
{
    // Map table for Arabic to English transliteration based on keyboard layout
    const std::unordered_map<wchar_t, wchar_t> ArabicToEnglishCharMap = {
        {L'ض', L'q'}, 
        {L'ص', L'w'}, 
        {L'ث', L'e'}, 
        {L'ق', L'r'}, 
        {L'ف', L't'}, 
        {L'غ', L'y'}, 
        {L'ع', L'u'}, 
        {L'ه', L'i'}, 
        {L'خ', L'o'}, 
        {L'ح', L'p'},
        {L'ج', L'['}, 
        {L'د', L']'},
        
        {L'ش', L'a'}, 
        {L'س', L's'}, 
        {L'ي', L'd'}, 
        {L'ب', L'f'}, 
        {L'ل', L'g'}, 
        {L'ا', L'h'}, 
        {L'ت', L'j'}, 
        {L'ن', L'k'}, 
        {L'م', L'l'},
        {L'ك', L';'}, 
        {L'ط', L'\''},
         
        {L'ئ', L'z'}, 
        {L'ء', L'x'}, 
        {L'ؤ', L'c'}, 
        {L'ر', L'v'}, 
        {L'ى', L'n'},
        {L'ة', L'm'}, 
        {L'و', L','}, 
        {L'ز', L'.'}, 
        {L'ظ', L'/'},

        {L'ذ', L'`'},

        {L' َ', L'Q'}, 
        {L' ً', L'W'},
        {L' ُ', L'E'},  
        {L' ٌ', L'R'},  
        {L'إ', L'Y'}, 
        {L'‘', L'U'}, 
        {L'÷', L'I'}, 
        {L'×', L'O'},
        {L'؛', L'P'}, 
        {L'<', L'{'}, 
        {L'>', L'}'}, 
        
        {L'ِ', L'A'}, 
        {L'ٍ', L'S'}, 
        {L']', L'D'}, 
        {L'[', L'F'}, 
        {L'أ', L'H'}, 
        {L'ـ', L'J'}, 
        {L'،', L'K'}, 
        {L'/', L'L'},
         
        {L'~', L'Z'}, 
        {L'\'ْ', L'X'}, 
        {L'}', L'C'}, 
        {L'{', L'V'}, 
        {L'آ', L'N'},
        {L'’', L'M'}, 
        {L',', L'<'}, 
        {L'.', L'>'}, 
        {L'؟', L'?'}
    };

    const std::unordered_map<wchar_t, wchar_t> EnglishToArabicCharMap = {
        {L'q', L'ض'}, 
        {L'w', L'ص'}, 
        {L'e', L'ث'}, 
        {L'r', L'ق'}, 
        {L't', L'ف'}, 
        {L'y', L'غ'}, 
        {L'u', L'ع'}, 
        {L'i', L'ه'}, 
        {L'o', L'خ'}, 
        {L'p', L'ح'},
        {L'[', L'ج'}, 
        {L']', L'د'},
      
        {L'a', L'ش'}, 
        {L's', L'س'}, 
        {L'd', L'ي'}, 
        {L'f', L'ب'}, 
        {L'g', L'ل'}, 
        {L'h', L'ا'}, 
        {L'j', L'ت'}, 
        {L'k', L'ن'}, 
        {L'l', L'م'},
        {L';', L'ك'}, 
        {L'\'', L'ط'},
         
        {L'z', L'ئ'}, 
        {L'x', L'ء'}, 
        {L'c', L'ؤ'}, 
        {L'v', L'ر'}, 
        {L'b', L'ل'}, 
        {L'n', L'ى'},
        {L'm', L'ة'}, 
        {L',', L'و'}, 
        {L'.', L'ز'}, 
        {L'/', L'ظ'},

        {L'`', L'ذ'},

        {L'Q', L' َ'}, 
        {L'W', L' ً'},
        {L'E', L' ُ'},  
        {L'R', L' ٌ'},  
        {L'T', L'ف'}, 
        {L'Y', L'إ'}, 
        {L'U', L'‘'}, 
        {L'I', L'÷'}, 
        {L'O', L'×'},
        {L'P', L'؛'}, 
        {L'{', L'<'}, 
        {L'}', L'>'}, 
        
        {L'A', L'ِ'}, 
        {L'S', L'ٍ'}, 
        {L'D', L']'}, 
        {L'F', L'['}, 
        {L'G', L'ل'}, 
        {L'H', L'أ'}, 
        {L'J', L'ـ'}, 
        {L'K', L'،'}, 
        {L'L', L'/'},
         
        {L'Z', L'~'}, 
        {L'X', L'\'ْ'}, 
        {L'C', L'}'}, 
        {L'V', L'{'}, 
        {L'B', L'ل'}, 
        {L'N', L'آ'},
        {L'M', L'’'}, 
        {L'<', L','}, 
        {L'>', L'.'}, 
        {L'?', L'؟'}
    };
}